Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its
application.

Ans:- min-max is a normalisation technique where we get all the values in range of 0 to 1, we use the formula = X_scaled = (X - X_min) / (X_max - X_min)

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
lis = np.array([1,2,3,4,5,1,2,3,4,5,1,2,3,4,5])
scaler = MinMaxScaler()
scaler.fit_transform(lis.reshape(-1, 1))


array([[0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ],
       [0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ],
       [0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ]])

Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling?
Provide an example to illustrate its application.

Ans: In contrast to Min-Max scaling, which scales the values of a feature to a fixed range between 0 and 1, Unit Vector scaling preserves the direction of the data points and only adjusts their magnitudes. Specifically, each data point is divided by the Euclidean norm of the feature vector:

X_norm = X / ||X||

where X is the original feature vector and ||X|| is its Euclidean norm.

In [2]:
lis

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [3]:
from sklearn.preprocessing import Normalizer

scaler = Normalizer()

# fit and transform the data
data_norm = scaler.fit_transform(lis.reshape(1, -1) )

print("Original data:\n", lis)
print("Normalized data:\n", data_norm)


Original data:
 [1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]
Normalized data:
 [[0.07784989 0.15569979 0.23354968 0.31139958 0.38924947 0.07784989
  0.15569979 0.23354968 0.31139958 0.38924947 0.07784989 0.15569979
  0.23354968 0.31139958 0.38924947]]


Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an
example to illustrate its application.

PCA is a statistical technique used to reduce the dimension by keeping maximum possible information it can retain.

PCA works by finding the directions of maximum variance in the data and projecting the data onto these directions, creating new variables that capture most of the variation in the original data. These new variables, called principal components, are linear combinations of the original variables and are uncorrelated with each other.

Consider the example of house price with 100 of columns, out of 100 we choose the first few principal components that capture the majority of the variability in the data and use them as new variables to represent the data in a lower-dimensional space.

Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature
Extraction? Provide an example to illustrate this concept.

Feature extraction is the process of transforming raw data into a smaller set of more meaningful features that can capture the most important information in the data. This is often done to simplify the data and reduce its dimensionality, which can improve the performance of machine learning algorithms and make the data easier to analyze and visualize.

PCA can be used as a feature extraction technique by finding the principal components of the data, which can be used as new features to represent the data in a lower-dimensional space.

example: Consider the example of house price with 100 of columns, out of 100 we choose the first few principal components that capture the majority of the variability in the data and use them as new variables to represent the data in a lower-dimensional space.

Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset
contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to
preprocess the data.

Ans:- as all the variable price, rating and delivery time is numeric value, hence we can use min-max scaling easily
we can apply this formula to scale the data

scaled_value = (original_value - min_value) / (max_value - min_value)

Q6. You are working on a project to build a model to predict stock prices. The dataset contains many
features, such as company financial data and market trends. Explain how you would use PCA to reduce the
dimensionality of the dataset.

Ans:- PCA can be used as a feature extraction technique by finding the principal components of the data, which can be used as new features to represent the data in a lower-dimensional space. So we will plot the data and find few feature with max variances, then plot the points on the line capturing all the points, then this new line gives a new feature , similarly se sellect few more features and use them as new data set hence left with fewer features.

Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the
values to a range of -1 to 1.

In [5]:
lis = np.array([1, 5, 10, 15, 20])
scaler = MinMaxScaler()
scaler.fit_transform(lis.reshape(-1,1))

array([[0.        ],
       [0.21052632],
       [0.47368421],
       [0.73684211],
       [1.        ]])

Q8. For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform
Feature Extraction using PCA. How many principal components would you choose to retain, and why?

Ans:-  We would choose the number of principal components to keep based on the amount of variance we want to retain in the data. we will do PCA and then according to result and our requirement we choose to retain the new features.